[package]
name = "plot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
charming = { version = "0.3.1", features = ["image", "ssr"] }
plotters = "0.3.3"
polars = "0.21"
polars-core = "0.21"
